export const TechnologyTags = [
      "Python",
      "JavaScript",
      "Java",
      "C++",
      "Ruby",
      "Go",
      "Swift",
      "Kotlin",
      "PHP",
      "Rust",
      "React",
      "Angular",
      "Node.js",
      "Flask",
      "Ruby on Rails",
      "Django",
      "TensorFlow",
      "PyTorch",
      "Spring Boot",
      "Express.js",
      "Visual Studio Code",
      "IntelliJ IDEA",
      "Eclipse",
      "Docker",
      "Git",
      "GitHub",
      "Bitbucket",
      "JIRA",
      "Confluence",
      "Jenkins",
      "MySQL",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Oracle Database",
      "SQL Server",
      "Cassandra",
      "Firebase",
      "Elasticsearch",
      "Neo4j",
      "AWS (Amazon Web Services)",
      "Azure",
      "Google Cloud Platform (GCP)",
      "Heroku",
      "DigitalOcean",
      "IBM Cloud",
      "Alibaba Cloud",
      "Kubernetes",
      "Docker Swarm",
      "Serverless",
      "Android",
      "iOS",
      "React Native",
      "Flutter",
      "Xamarin",
      "HTML5",
      "CSS3",
      "WebSockets",
      "RESTful APIs",
      "GraphQL",
      "Progressive Web Apps (PWAs)",
      "Unit Testing",
      "Integration Testing",
      "Test Automation",
      "Selenium",
      "JUnit",
      "TestNG",
      "Postman",
      "JIRA (for tracking bugs)",
      "Continuous Integration (CI)",
      "Continuous Deployment (CD)",
      "Kubernetes",
      "Docker Swarm",
      "Ansible",
      "Terraform",
      "Jenkins",
      "Travis CI",
      "Cybersecurity",
      "Authentication",
      "Authorization",
      "Encryption",
      "OWASP (Open Web Application Security Project)",
      "Security Testing",
      "Agile",
      "Scrum",
      "Kanban",
      "Project Management Tools",
      "Collaboration Tools",
      "Data Analysis",
      "Machine Learning",
      "Natural Language Processing (NLP)",
      "Computer Vision",
      "Data Visualization",
      "TensorFlow",
      "PyTorch",
      "IoT Devices",
      "IoT Protocols (e.g., MQTT, CoAP)",
      "IoT Platforms (e.g., AWS IoT, Azure IoT)",
      "Sensor Networks",
      "VirtualBox",
      "VMware",
      "Kubernetes",
      "Docker",
      "Container Orchestration",
      "CPUs",
      "GPUs",
      "Motherboards",
      "RAM",
      "Storage (e.g., SSD, HDD)",
      "Blockchain",
      "Smart Contracts",
      "Augmented Reality (AR)",
      "Virtual Reality (VR)",
      "Quantum Computing",
      "Big Data",
      "Hadoop",
      "Spark",
      "NoSQL Databases",
      "Microservices",
      "API Gateway",
      "WebAssembly",
      "Serverless Computing",
      "Blockchain",
      "Smart Contracts",
      "Quantum Computing",
      "Edge Computing",
      "FPGA",
      "3D Printing",
      "Biotechnology",
      "Nanotechnology",
      "Robotics",
      "Artificial Intelligence (AI)",
      "Machine Learning Operations (MLOps)",
    ];